appName: my-app  

service: frontend 

deployment:
  image:
    repository: tferrari92/my-app-frontend 
    tag: 13
  replicas: 1

  labels:
    system: my-app
    service: frontend
    app: my-app-frontend
    backstage.io/kubernetes-id: my-app-frontend

  env: