apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app-backend
  description: My-App Backend Service
  annotations:
    backstage.io/kubernetes-id: backend
  tags:
    - nodejs
  links:
    - title: Documentation
      url: https://github.com/tomasferrarisenda/backstage-minikube-lab
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://grafana.domain.com/
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://grafana.domain.com/
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: service
  lifecycle: production
  owner: my-app-backend-subteam
  system: my-app
  # dependsOn:
  #   - component: my-app-redis
  dependsOn:
    - resource:default/my-app-redis
  # providesApis:
  #   - my-app-frontend