site_name: My-App Backend Service Documentation
site_description: Comprehensive documentation for the My-App Backend Service.
site_author: My-App Backend Subteam
site_url: https://yourdocumentation.site/docs/my-app-backend

# Repository where the source code is hosted
repo_url: https://github.com/tomasferrarisenda/backstage-minikube-lab
edit_uri: edit/main/docs/my-app-backend

# Navigation structure for the documentation
nav:
  - Overview: index.md
  - Setup Guide:
    - Installation: setup/installation.md
    - Configuration: setup/configuration.md
  - API Reference:
    - REST API: api-reference/rest-api.md
    - Authentication: api-reference/authentication.md
  - Operational Insights:
    - Monitoring: operational-insights/monitoring.md
    - Logging: operational-insights/logging.md
    - Dependencies: operational-insights/dependencies.md
  - About:
    - Team: about/team.md
    - Contributing: about/contributing.md

# Theme configuration
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    primary: deep purple
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono

# Plugins used in the documentation
plugins:
  - search
  - techdocs-core

# Markdown extensions for enhanced features
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
