apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-nodejs-existing-repo
  title: New Node.js in existing repo
  description: Create directory for new NodeJS service in existing repo
spec:
  owner: your-team-name
  type: service

  parameters:
    - title: Fill in the details for your new service folder
      required:
        - name
      properties:
        name:
          type: string
          title: Folder Name
          description: The name of the new service folder to be created.

  steps:
    - id: fetchBase
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./path/to/your/base/template
        values:
          name: ${{ parameters.name }}

    - id: prepareFolder
      name: Prepare New Folder
      action: fetch:cookiecutter
      input:
        url: ${{ steps.fetchBase.output.folder }}
        values:
          name: ${{ parameters.name }}
        # This step assumes the use of cookiecutter to prepare the folder structure.
      
    - id: customGitOperation
      name: Custom Git Operation
      action: custom:git:commit
      input:
        repoUrl: https://github.com/tomasferrarisenda/backstage
        targetPath: /my-app/${{ parameters.name }}
        commitMessage: 'Adding new service folder: ${{ parameters.name }}'
        branch: main
        # This action should be a custom action you've defined to handle Git operations.
        # You'll need to implement or configure an action to clone the repo, add your folder, and push.

  output:
    createdFolderUrl: ${{ steps.customGitOperation.output.folderUrl }}
