apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-nodejs-existing-repo
  title: New Node.js in existing repo
  description: Create directory for new NodeJS service in existing repo
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: App Name
          type: string
          description: Unique name for your app
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a Repo location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    # Step to setup a workspace and clone the repository
    - id: setup
      name: Setup Repository
      action: fetch:cookiecutter
      input:
        url: ${{ parameters.repoUrl }}
        outputPath: "./workspace"

    # Step to create a new branch in the cloned repository
    - id: create-branch
      name: Create Branch
      action: git:create-branch
      input:
        branchName: "add-my-app-${{ parameters.name }}"

    # Step to add new directory with contents to the branch
    - id: add-directory
      name: Add Directory
      action: file:write
      input:
        path: "./workspace/my-app/${{ parameters.name }}"
        content: ${{ steps.fetch-base.output.content }}

    # Step to commit and push the changes to the remote repository
    - id: commit-and-push
      name: Commit and Push
      action: git:commit-push
      input:
        message: "Add new app directory my-app/${{ parameters.name }}"

    # Step to create a pull request for the new branch
    - id: create-pr
      name: Create Pull Request
      action: github:create-pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: "add-my-app-${{ parameters.name }}"
        title: "Add ${parameters.name} app directory"
        description: "Adding a new directory `my-app/${parameters.name}` for the Node.js app deployment on AWS EKS using Terraform."

  output:
    links:
      - title: Pull Request
        url: ${{ steps['create-pr'].output.pullRequestUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
