parameters:
  - name: APP_NAME
  - name: SERVICE_NAME
  - name: DOCKERHUB_USERNAME

stages:
- stage: BuildApp
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      displayName: Build And Push Image
      inputs:
        containerRegistry: 'dockerhub'
        repository: '${{ parameters.DOCKERHUB_USERNAME }}/${{ parameters.APP_NAME }}-${{ parameters.SERVICE_NAME }}'
        command: 'buildAndPush'
        Dockerfile: 'my-app/backend/Dockerfile'