name: build-and-deploy-service

trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - my-app/backend/*

parameters:
  - name: SERVICE_NAME
    displayName: 'Introduce the name of the service'
    type: string

variables:
  # - group: aws-keys
  # - name: AWS_REGION
  #   value: us-east-1  # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: gonchi # This value was modified by the initial-setup python script
  - name: DOCKERHUB_USERNAME
    value: tferrari92 # This value was modified by the initial-setup python script
  - name: USER_EMAIL
    value: tomas.ferrari@sendati.com # This value was modified by the initial-setup python script
    
pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created

stages:
- template: templates/build-docker-image.yml
  parameters: 
    APP_NAME: $(APP_NAME)
    SERVICE_NAME: ${{ parameters.SERVICE_NAME }}
    DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)

# - template: templates/deploy-dev.yml
#     SERVICE_NAME: ${{ parameters.SERVICE_NAME }}

# - template: templates/deploy-stage.yml
#     SERVICE_NAME: ${{ parameters.SERVICE_NAME }}

# - template: templates/deploy-prod.yml
#     SERVICE_NAME: ${{ parameters.SERVICE_NAME }}
#     USER_EMAIL: $(USER_EMAIL)
