apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
  description: ${{ values.name }} NodeJS App
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
