apiVersion: v1
kind: Service
metadata:
  name: my-app-frontend-service
  namespace: my-app
spec:
  selector:
    app: my-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP