apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kratos
spec:
  profile:
    displayName: Kratos
    email: kratos@sparta.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf:
    - platform-team