apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "middleend"
  annotations:
    backstage.io/kubernetes-id: middleend
  description: middleend NodeJS App
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
