appName: my-app

service: backend

containerPort: 3000 # Port where the app in the container exposes the service

deployment:
  image:
    repository: tferrari92/my-app-backend # This value was modified by the initial-setup python script