apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: all-users
  description: A collection of all Backstage users
spec:
  targets:
    - ./users/geralt.yaml
    - ./users/kratos.yaml
    - ./users/masterchief.yaml
    