replica:
  replicaCount: 1

auth:
  enabled: false

# This annotation doesn't work in objects of kind Resource. It only works in objects of kind Component.
# Our Redis deployment is registered as a Resource in Backstege catalog, so we can't use this annotation unless we change the kind of the object to Component.
# commonLabels:
#   backstage.io/kubernetes-id: my-app-redis