apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend-deployment
  namespace: my-app
  labels:
    app: "my-app-backend"
    backstage.io/kubernetes-id: "my-app-backend"
    service: "backend"
    system: "my-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "my-app-backend"
      service: "backend"
      system: "my-app"
  template:
    metadata:
      labels:
        app: "my-app-backend"
        backstage.io/kubernetes-id: "my-app-backend"
        service: "backend"
        system: "my-app"
    spec:
      containers:
        - name: my-app-backend
          image: tferrari92/my-app-backend:backstage-minikube-lab
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-master