apiVersion: v1
kind: Service
metadata:
  name: ${{ values.system }}-${{ values.service }}-service
  namespace: ${{ values.system }}
spec:
  selector:
    app: ${{ values.system }}-${{ values.service }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP