apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-{{ .Values.service }}-service
spec:
  selector:
    app: {{ .Values.appName }}-{{ .Values.service }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP