parameters:
  - name: SERVICE_NAME
    displayName: 'Introduce the name of the service'
    type: string


stages:
- stage: BuildApp
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '17.09.0-ce'

    - task: Docker@2
      displayName: Build And Push Image
      inputs:
        containerRegistry: 'dockerhub'
        repository: '$(DOCKERHUB_USERNAME)/$(APP_NAME)-${{ parameters.SERVICE_NAME }}'
        command: 'buildAndPush'
        Dockerfile: 'my-app/backend/Dockerfile'