name: Build & push my-app-backend-2 image

on:
  push:
    branches:
      - main
    paths:
      - 'my-app/backend-2/**'

env:
  SYSTEM: my-app
  SERVICE: backend-2

jobs:
  build-and-push:
    name: Build & push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.SYSTEM }}-${{ env.SERVICE }}
          tag: ${{ github.run_number }}
          registry: docker.io
          directory: ${{ env.SYSTEM }}/${{ env.SERVICE }}
          dockerfile: ${{ env.SYSTEM }}/${{ env.SERVICE }}/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}